Website = "https://github.com/ic1149/quicktraintimes"

[Details]
  Icon = "qtt_icon_v1.png"
  Name = "quicktraintimes"
  ID = "io.github.ic1149.qtt"
  Version = "1.0.5"
  Build = 24

[LinuxAndBSD]
  GenericName = "Quick Train Times"
  Comment = "Get UK National Rail train times quickly."
